modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/MCLegoMan/ashore/issues"
license = "LGPL-3.0-or-later"

[[mods]]
modId = "ashore"
version = "${version}"
displayName = "Ashore"
displayURL = "https://github.com/MCLegoMan/ashore"
logoFile = "icon.png"
authors = "MCLegoMan"
description = '''Switches boat velocity. Boats are now faster on land than in water!'''

[[dependencies.ashore]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ashore]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "ashore.mixins.json"
